export const urls = {
    APP: {
        LOGIN: "/login",
        REGISTER: "/register",
        FORGOTTEN_PASSWORD: "/forgottenPassword",
        UPDATE_PASSWORD: "/updatePassword",
        DASHBOARD: "/",
        PROFILE: "/profile",
        SUBSCRIBE: "/subscribe",
    },
    API: {
        LOGIN: "/users/login",
        REGISTER: "/users/register",
        FORGOTTEN_PASSWORD: "/users/sendEmailToResetPassword",
        CHECK_TOKEN: "/users/checkToken",
        UPDATE_PASSWORD: "/users/updatePassword",
        PROFILE: "/users/profile",
        GET_ALL_FOLDERS: "/folders/getAll",
        GET_ALL_NOTES: "/notes/getAll",
        CREATE_FOLDER: "/folders/createFolder",
        CREATE_NOTE: "/notes/createNote",
        DELETE_FOLDER: "/folders/deleteFolder",
        DELETE_NOTE: "/notes/deleteNote",
    },
}
